# Generated by Django 4.0.3 on 2022-03-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mch_album',
            new_name='mch_albumM',
        ),
    ]
