# Generated by Django 4.0.3 on 2022-04-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_postcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('name', models.CharField(max_length=20, verbose_name='なまえ')),
                ('age', models.IntegerField()),
                ('explanation', models.TextField(default='---', verbose_name='情報')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='album.postcategory', verbose_name='カテゴリー')),
            ],
        ),
        migrations.DeleteModel(
            name='mch_albumM',
        ),
    ]
