# Generated by Django 4.0.3 on 2022-05-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_albumm_delete_mch_albumm'),
    ]

    operations = [
        migrations.CreateModel(
            name='mkSelectM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(verbose_name='年代')),
                ('memo_id', models.IntegerField(verbose_name='流れ')),
                ('ko_id', models.IntegerField(verbose_name='Article')),
            ],
        ),
    ]
